[package]
name = "serde_amp"
version = "0.3.0"
description = "serde support for Asynchronous Messaging Protocol (AMP) boxes"
keywords = ["serde", "serialization", "amp"]
categories = ["encoding"]
readme = "README.md"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
include = [
    "src/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[dependencies]
amp-protocol = { path = "../amp-protocol", version = "0.1" }
serde.workspace = true

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
